name: main
on:
  push:
    branches:
      - "main"
jobs:
  tests:
    name: python-${{ matrix.python-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: ["macOS-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: setup-python-${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-requirements
        run: |
          python -m pip install --upgrade pip tox tox-gh-actions
          python -m pip install -e .
      - name: run-tests
        run: tox
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-python-3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install-requirements
        run: |
          python -m pip install --upgrade pip tox tox-gh-actions
          python -m pip install -e .
      - name: lint
        run: tox -e lint
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-python-3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install-requirements
        run: |
          python -m pip install --upgrade pip tox tox-gh-actions
          python -m pip install -e .
      - name: docs
        run: tox -e docs
